name: Bug Report
description: Report a bug
title: '[Bug]: '
labels: bug
body:
  - type: input
    id: contact
    attributes:
      value: some info
  - type: markdown
    attributes:
      value: Provide as much information as possible to help us investigate the bug.
